lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: login
#    token_extractors:
#        cookie:
#            enabled: true
#            name: user_auth
#    set_cookies:
#        user_auth: ~
#
#    remove_token_from_body_when_cookies_used: false
