controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: annotation
kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: annotation
users:
    resource: ../src/Users/Infrastructure/Controller/
    type: annotation